apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifacts-ssd
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  storageClassName: sstorage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
