argoCdConfigs:
  secretMap:
    vaam-eat-aio-repo:
      type: repository
      data:
        url: "https://github.com/vaam-store/vaam-eat-aio"
        name: vaam-eat-aio
        type: git
    apple-health-export:
      type: repository
      data:
        url: "https://whythatfunction.github.io/apple-health-export"
        name: apple-health-export
        type: helm

applications:
  - name: jellyfin
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: external
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/home-apps/jellyfin
    destination:
      server: https://kubernetes.default.svc
      namespace: jellyfin
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: keycloak-ha
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: keycloak
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/home-apps/keycloak-ha
      helm:
        valuesObject:
          keycloak:
            ingress:
              main:
                enabled: false
          db:
            enabled: true
    destination:
      name: home-remote
      namespace: keycloak
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

  - name: redis-ha
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: redis
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/home-apps/redis-ha

    destination:
      name: home-remote
      namespace: redis-system
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

  - name: endpoints
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: external
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/home-apps/endpoints
    destination:
      server: https://kubernetes.default.svc
      namespace: endpoints
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  - name: keycloak-backup
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: keycloak
    source:
      repoURL: https://github.com/ADORSYS-GIS/ai-helm
      targetRevision: HEAD
      path: charts/keycloak-backup
      helm:
        releaseName: keycloak-backup
        valueFiles:
          - values.yaml
        valuesObject:
          app-template:
            adminSecret: keycloak-pg-app
            dbSecret: keycloak-pg-app
            s3Secret: keycloak-s3
            controller:
              main:
                initContainer:
                  exporter:
                    image:
                      tag: "26.0"
    destination:
      server: https://kubernetes.default.svc
      namespace: keycloak
    syncPolicy:
      syncOptions:
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true