argoCdConfigs:
  secretMap:
    vaam-eat-aio-repo:
      type: repository
      data:
        url: "https://github.com/vaam-store/vaam-eat-aio"
        name: vaam-eat-aio
        type: git
    apple-health-export:
      type: repository
      data:
        url: "https://whythatfunction.github.io/apple-health-export"
        name: apple-health-export
        type: helm

applications:
  - name: jellyfin
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: external
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/home-apps/jellyfin
    destination:
      server: https://kubernetes.default.svc
      namespace: jellyfin
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: adminer
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: external
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/home-apps/adminer
    destination:
      server: https://kubernetes.default.svc
      namespace: adminer
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: keycloak
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: keycloak
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/home-apps/keycloak
    destination:
      server: https://kubernetes.default.svc
      namespace: keycloak
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  - name: keycloak-ha
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: keycloak
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/home-apps/keycloak-ha
      helm:
        valuesObject:
          keycloak:
            ingress:
              main:
                enabled: false
    destination:
      name: home-remote
      namespace: keycloak
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

  - name: redis-ha
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: redis
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/home-apps/redis-ha
      helm:
        valuesObject:
          global:
            redisinsight:
              dns: redisinsight.ssegning.com
          ingress:
            redisinsight:
              annotations:
                cert-manager.io/cluster-issuer: cert-cloudflare
          rawResources:
            redis-tls:
              spec:
                issuerRef:
                  kind: ClusterIssuer
                  name: self-signed-ca
                  group: cert-manager.io
            sentinel-tls:
              spec:
                issuerRef:
                  kind: ClusterIssuer
                  name: self-signed-ca
                  group: cert-manager.io
            redisinsight-tls:
              spec:
                issuerRef:
                  kind: ClusterIssuer
                  name: cert-cloudflare
                  group: cert-manager.io
                dnsNames:
                  - "redisinsight.ssegning.com"
                
    destination:
      name: home-remote
      namespace: redis-system
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

  - name: endpoints
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: external
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/home-apps/endpoints
    destination:
      server: https://kubernetes.default.svc
      namespace: endpoints
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  - name: music
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: external
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/home-apps/music
    destination:
      server: https://kubernetes.default.svc
      namespace: music
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: portainer
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: default
    source:
      repoURL: https://portainer.github.io/k8s/
      targetRevision: 2.33.1
      chart: portainer
      helm:
        valuesObject:
          persistence:
            storageClass: longhorn

          service:
            type: ClusterIP

          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: self-signed-ca
            tls:
              - secretName: portainer-tls
                hosts:
                  - portainer.home.ssegning
            hosts:
              - host: portainer.home.ssegning
                paths:
                  - path: /
    destination:
      server: https://kubernetes.default.svc
      namespace: portainer
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: keycloak-backup
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: keycloak
    source:
      repoURL: https://github.com/ADORSYS-GIS/ai-helm
      targetRevision: HEAD
      path: charts/keycloak-backup
      helm:
        releaseName: keycloak-backup
        valueFiles:
          - values.yaml
        valuesObject:
          app-template:
            adminSecret: keycloak-pg-app
            dbSecret: keycloak-pg-app
            s3Secret: keycloak-s3
            controller:
              main:
                initContainer:
                  exporter:
                    image:
                      tag: "26.0"
    destination:
      server: https://kubernetes.default.svc
      namespace: keycloak
    syncPolicy:
      syncOptions:
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

  - name: lakefs
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: ml
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/ml/lake-fs
    destination:
      server: https://kubernetes.default.svc
      namespace: lakefs
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

  - name: mlflow
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: ml
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/ml/mlflow
    destination:
      server: https://kubernetes.default.svc
      namespace: mlflow
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

  - name: vaam-store-ml-platform
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: vaam-store
    source:
      repoURL: https://github.com/vaam-store/vaam-store-ml
      targetRevision: HEAD
      path: helm/ml-platform
      helm:
        valuesObject:
          global:
            imagePullSecrets:
              - name: gh-pat
    destination:
      server: https://kubernetes.default.svc
      namespace: vaam-store-ml-platform
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

  - name: kyc-storage
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: kyc
    source:
      repoURL: oci://ghcr.io/adorsys-gis/charts/user-storage
      targetRevision: 0.1.0
      chart: .
      helm:
        valuesObject:
          controllers:
            user-storage:
              initContainers:
                migrate:
                  env:
                    DATABASE_URL:
                      valueFrom:
                        secretKeyRef:
                          name: "{{ .Release.Name }}-db-app"
                          key: uri
              containers:
                user-storage:
                  env:
                    DATABASE_URL:
                      valueFrom:
                        secretKeyRef:
                          name: "{{ .Release.Name }}-db-app"
                          key: uri
                    REDIS_URL: "redis://redis-master.database.svc.cluster.local:6379"
                    RUST_LOG: "info"
                    OTEL_SERVICE_NAME: "user-storage-backend"
                    OTEL_EXPORTER_OTLP_ENDPOINT: "http://{{ .Release.Name }}-otel-collector:4317"
            worker:
              containers:
                worker:
                  env:
                    DATABASE_URL:
                      valueFrom:
                        secretKeyRef:
                          name: "{{ .Release.Name }}-db-app"
                          key: uri
                    REDIS_URL: "redis://redis-master.database.svc.cluster.local:6379"
                    RUST_LOG: "info"
                    OTEL_SERVICE_NAME: "user-storage-worker"
                    OTEL_EXPORTER_OTLP_ENDPOINT: "http://{{ .Release.Name }}-otel-collector:4317"
          ingress:
            user-storage:
              className: traefik
              annotations:
                cert-manager.io/cluster-issuer: cert-cloudflare
              hosts:
                - host: api.verif.fyi
                  paths:
                    - path: /
                      pathType: Prefix
                      service:
                        identifier: user-storage
                        port: http
              tls:
                - secretName: api.verif.fyi-tls
                  hosts:
                    - api.verif.fyi
          rawResources:
            db:
              enabled: true
              apiVersion: postgresql.cnpg.io/v1
              kind: Cluster
              spec:
                spec:
                  instances: 2
                  storage:
                    size: 10Gi
                    storageClass: longhorn
                  resources:
                    requests:
                      memory: "512Mi"
                      cpu: "500m"
                    limits:
                      memory: "1Gi"
                      cpu: "1"
            otel:
              enabled: true
              apiVersion: opentelemetry.io/v1beta1
              kind: OpenTelemetryCollector
              spec:
                spec:
                  config:
                    receivers:
                      otlp:
                        protocols:
                          grpc:
                            endpoint: 0.0.0.0:4317
                          http:
                            endpoint: 0.0.0.0:4318

                    processors:
                      batch: { }

                    exporters:
                      debug: { }

                    service:
                      pipelines:
                        traces:
                          receivers:
                            - otlp
                          processors:
                            - batch
                          exporters:
                            - debug
    destination:
      name: home-remote
      namespace: kyc-store
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true