applications:
  - name: cert
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: infrastructure
    source:
      repoURL: https://github.com/whythatfunction/home-os
      targetRevision: HEAD
      path: charts/cert
    destination:
      server: https://kubernetes.default.svc
      namespace: kube-system
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  - name: cert-remote
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: infrastructure
    sources:
      - repoURL: https://github.com/whythatfunction/home-os
        targetRevision: HEAD
        path: charts/cert
        helm:
          releaseName: cert

      - repoURL: https://bjw-s-labs.github.io/helm-charts
        targetRevision: "4.*"
        chart: app-template
        helm:
          valuesObject:
            rawResources:
              cloudflare-api-secret:
                enabled: true
                apiVersion: external-secrets.io/v1
                kind: ExternalSecret
                spec:
                  spec:
                    refreshInterval: 0h10m0s
                    secretStoreRef:
                      name: ssegning-aws
                      kind: ClusterSecretStore
                    target:
                      name: cloudflare-secret
                      creationPolicy: Owner
                    data:
                      - secretKey: api-token
                        remoteRef:
                          key: "prod/meta/test-app"
                          property: cloudflare_token
    destination:
      name: home-remote
      namespace: kube-system
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  - name: cert-netcup
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: infrastructure
    sources:
      - repoURL: https://github.com/whythatfunction/home-os
        targetRevision: HEAD
        path: charts/cert
        helm:
          releaseName: cert

      - repoURL: https://bjw-s-labs.github.io/helm-charts
        targetRevision: "4.*"
        chart: app-template
        helm:
          valuesObject:
            rawResources:
              cloudflare-api-secret:
                enabled: true
                apiVersion: external-secrets.io/v1
                kind: ExternalSecret
                spec:
                  spec:
                    refreshInterval: 0h10m0s
                    secretStoreRef:
                      name: ssegning-aws
                      kind: ClusterSecretStore
                    target:
                      name: cloudflare-secret
                      creationPolicy: Owner
                    data:
                      - secretKey: api-token
                        remoteRef:
                          key: "prod/meta/test-app"
                          property: cloudflare_token
    destination:
      name: netcup-k8s
      namespace: kube-system
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

