{{ range $key, $val := .Values.secretStores }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ include "common.tplvalues.render" ( dict "value" $key "context" $ ) }}
  labels:
    {{ include "common.labels.matchLabels" $ | nindent 4 }}
spec:
  provider:
    {{ include "common.tplvalues.render" ( dict "value" $val "context" $ ) | nindent 4 }}
{{ end }}
