db:
  enabled: true
  instances: 2
  storage:
    size: 10Gi
    storageClass: longhorn
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

harbor:
  expose:
    ingress:
      hosts:
        core: container-registry.ssegning.com
      className: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: cert-cloudflare
  externalURL: https://container-registry.ssegning.com
  persistence:
    persistentVolumeClaim:
      registry:
        storageClass: longhorn
      jobservice:
        jobLog:
          storageClass: longhorn
      database:
        storageClass: longhorn
      redis:
        storageClass: longhorn
      trivy:
        storageClass: longhorn
  database:
    type: "external"
    external:
      host: registry-pg-rw
      username: app
      existingSecret: registry-pg-app
      coreDatabase: app
  redis:
    type: external
    external:
      addr: "redis-master.database.svc.cluster.local"

verdaccio:
  persistence:
    storageClass: longhorn
    size: 10Gi
  existingSecret: "npm-basic-auth"
  secrets:
    htpasswd: ~
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      cert-manager.io/cluster-issuer: cert-cloudflare
    # Use this to define, ALB ingress's actions annotation based routing. Ex: for ssl-redirect
    # Ref: https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/tasks/ssl_redirect/
    extraPaths: [ ]
    labels: { }
    hosts:
      - npm-registry.ssegning.com
    tls:
      - secretName: npm-registry-ssegning-com-tls
        hosts:
          - npm-registry.ssegning.com
  cachingNginx:
    enabled: true
