global:
  redis:
    image:
      repository: redis
      tag: "8.6.2-trixie"
  redisinsight:
    image:
      repository: redis/redisinsight
      tag: "3.4.2"
    dns: redisinsight.apps.verif.fyi
  oauth2Proxy:
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: "v7.8.1"

controllers:
  redis:
    type: statefulset
    replicas: 3

    podDisruptionBudget:
      enabled: true
      minAvailable: 2

    statefulset:
      podManagementPolicy: Parallel
      volumeClaimTemplates:
        - name: data
          accessMode: ReadWriteOnce
          size: 5Gi
          #storageClass: your-rwo-sc
          globalMounts:
            - path: /data

    containers:
      app:
        image:
          repository: "{{ $.Values.global.redis.image.repository }}"
          tag: "{{ $.Values.global.redis.image.tag }}"

        env:
          POD_NAME:
            fieldRef:
              fieldPath: metadata.name
          POD_NAMESPACE:
            fieldRef:
              fieldPath: metadata.namespace
          MASTER_FQDN: "{{ $.Release.Name }}-redis-0.{{ $.Release.Name }}-redis-headless.{{ $.Release.Namespace }}.svc.cluster.local"
          RELEASE_NAME: "{{ $.Release.Name }}"

        command:
          - /bin/sh
          - -ec
        args:
          - |
            ORDINAL="${POD_NAME##*-}"
            POD_FQDN="${POD_NAME}.${RELEASE_NAME}-redis-headless.${POD_NAMESPACE}.svc.cluster.local"

            mkdir -p /data
            cp /bootstrap/redis.conf /data/redis.conf

            {
              echo "dir /data"
              echo "appendonly yes"
              echo "replica-announce-port 6379"
              echo "replica-announce-ip ${POD_FQDN}"
            } >> /data/redis.conf

            if [ "${ORDINAL}" != "0" ]; then
              echo "replicaof ${MASTER_FQDN} 6379" >> /data/redis.conf
            fi

            exec redis-server /data/redis.conf

        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 6379
              initialDelaySeconds: 10
              periodSeconds: 10
          readiness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 6379
              initialDelaySeconds: 5
              periodSeconds: 5
          startup:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 6379
              failureThreshold: 30
              periodSeconds: 5

        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            memory: 1Gi

  sentinel:
    type: statefulset
    replicas: 3

    podDisruptionBudget:
      enabled: true
      minAvailable: 2

    statefulset:
      podManagementPolicy: Parallel
      volumeClaimTemplates:
        - name: data
          accessMode: ReadWriteOnce
          size: 1Gi
          #storageClass: your-rwo-sc
          globalMounts:
            - path: /data

    containers:
      app:
        image:
          repository: "{{ $.Values.global.redis.image.repository }}"
          tag: "{{ $.Values.global.redis.image.tag }}"

        env:
          POD_NAME:
            fieldRef:
              fieldPath: metadata.name
          POD_NAMESPACE:
            fieldRef:
              fieldPath: metadata.namespace
          MASTER_NAME: "{{ $.Release.Name }}"
          MASTER_FQDN: "{{ $.Release.Name }}-redis-0.{{ $.Release.Name }}-redis-headless.{{ .Release.Namespace }}.svc.cluster.local"
          RELEASE_NAME: "{{ $.Release.Name }}"

        command:
          - /bin/sh
          - -ec
        args:
          - |
            POD_FQDN="${POD_NAME}.${RELEASE_NAME}-sentinel-headless.${POD_NAMESPACE}.svc.cluster.local"

            mkdir -p /data

            if [ ! -f /data/sentinel.conf ]; then
              cp /bootstrap/sentinel.conf /data/sentinel.conf

              {
                echo "sentinel monitor ${MASTER_NAME} ${MASTER_FQDN} 6379 2"
                echo "sentinel down-after-milliseconds ${MASTER_NAME} 5000"
                echo "sentinel failover-timeout ${MASTER_NAME} 60000"
                echo "sentinel parallel-syncs ${MASTER_NAME} 1"
                echo "sentinel resolve-hostnames yes"
                echo "sentinel announce-hostnames yes"
                echo "sentinel announce-ip ${POD_FQDN}"
                echo "sentinel announce-port 26379"
              } >> /data/sentinel.conf
            fi

            exec redis-sentinel /data/sentinel.conf

        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 26379
              initialDelaySeconds: 10
              periodSeconds: 10
          readiness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 26379
              initialDelaySeconds: 5
              periodSeconds: 5
          startup:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 26379
              failureThreshold: 30
              periodSeconds: 5

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 256Mi

  redisinsight:
    type: deployment
    replicas: 1

    containers:
      app:
        image:
          repository: "{{ $.Values.global.redisinsight.image.repository }}"
          tag: "{{ $.Values.global.redisinsight.image.tag }}"
        env:
          RI_APP_HOST: "0.0.0.0"
          RI_APP_PORT: "5540"
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 5540
              initialDelaySeconds: 20
              periodSeconds: 10
          readiness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 5540
              initialDelaySeconds: 10
              periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi

      oauth2-proxy:
        image:
          repository: "{{ $.Values.global.oauth2Proxy.image.repository }}"
          tag: "{{ $.Values.global.oauth2Proxy.image.tag }}"
        args:
          - --http-address=0.0.0.0:4180
          - --provider=keycloak-oidc
          - --cookie-secure=true
          - --cookie-samesite=lax
          - --set-xauthrequest=true
          - --pass-access-token=true
          - --pass-authorization-header=true
          - --oidc-issuer-url=$(OAUTH2_PROXY_ISSUER)
          - --client-id=$(OAUTH2_PROXY_CLIENT_ID)
          - --client-secret=$(OAUTH2_PROXY_CLIENT_SECRET)
          - --cookie-secret=$(OAUTH2_PROXY_COOKIE_SECRET)
          - --redirect-url=$(OAUTH2_PROXY_URL)/oauth2/callback
          - --reverse-proxy=true
          - --upstream=static://202
          - --email-domain=*
          - --code-challenge-method=S256
        env:
          OAUTH2_PROXY_URL: "https://{{ $.Values.global.redisinsight.dns }}"
          OAUTH2_PROXY_ISSUER: "https://auth.verif.fyi/realms/ssegning-internal"
          OAUTH2_PROXY_CLIENT_ID:
            valueFrom:
              secretKeyRef:
                name: '{{ .Release.Name }}-oauth2-creds'
                key: client-id
          OAUTH2_PROXY_CLIENT_SECRET:
            valueFrom:
              secretKeyRef:
                name: '{{ .Release.Name }}-oauth2-creds'
                key: client-secret
          OAUTH2_PROXY_COOKIE_SECRET:
            valueFrom:
              secretKeyRef:
                name: '{{ .Release.Name }}-oauth2-creds'
                key: cookie-secret
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 4180
              initialDelaySeconds: 10
              periodSeconds: 10
          readiness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 4180
              initialDelaySeconds: 5
              periodSeconds: 5
defaultPodOptions:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: '{{ $.Release.Name }}'

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: '{{ $.Release.Name }}'

service:
  redis:
    controller: redis
    primary: true
    type: ClusterIP
    ports:
      redis:
        port: 6379
        protocol: TCP

  redis-headless:
    controller: redis
    type: ClusterIP
    clusterIP: None
    publishNotReadyAddresses: true
    ports:
      redis:
        port: 6379
        protocol: TCP

  sentinel:
    controller: sentinel
    primary: true
    type: ClusterIP
    ports:
      sentinel:
        port: 26379
        protocol: TCP

  sentinel-headless:
    controller: sentinel
    type: ClusterIP
    clusterIP: None
    publishNotReadyAddresses: true
    ports:
      sentinel:
        port: 26379
        protocol: TCP

  redisinsight:
    controller: redisinsight
    type: ClusterIP
    ports:
      http:
        port: 5540
        protocol: TCP
      oauth2:
        port: 4180
        protocol: TCP

ingress:
  redisinsight-auth2:
    hosts:
      - host: "{{ $.Values.global.redisinsight.dns }}"
        paths:
          - path: /oauth2
            pathType: Prefix
            service:
              identifier: redisinsight
              port: oauth2
    tls:
      - secretName: "{{ $.Release.Name }}-redisinsight-tls"
        hosts:
          - "{{ $.Values.global.redisinsight.dns }}"
  redisinsight:
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: "{{ $.Release.Namespace }}-{{ $.Release.Name }}-redisinsight-oauth2-errors@kubernetescrd,{{ $.Release.Namespace }}-{{ $.Release.Name }}-redisinsight-auth@kubernetescrd"
    hosts:
      - host: "{{ $.Values.global.redisinsight.dns }}"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: redisinsight
              port: http
    tls:
      - secretName: "{{ $.Release.Name }}-redisinsight-tls"
        hosts:
          - "{{ $.Values.global.redisinsight.dns }}"

configMaps:
  redis-bootstrap:
    enabled: true
    data:
      redis.conf: |
        bind 0.0.0.0
        protected-mode yes

        port 0
        tls-port 6379

        tls-cert-file /tls/tls.crt
        tls-key-file /tls/tls.key
        tls-ca-cert-file /tls/ca.crt

        # Keep this if you want Redis clients to use only server-auth TLS.
        # Remove it if you want true mTLS for every client.
        tls-auth-clients no

        # Required so replica -> master links use TLS
        tls-replication yes

        save 900 1
        save 300 10
        save 60 10000

  sentinel-bootstrap:
    enabled: true
    data:
      sentinel.conf: |
        bind 0.0.0.0

        port 0
        tls-port 26379

        tls-cert-file /tls/tls.crt
        tls-key-file /tls/tls.key
        tls-ca-cert-file /tls/ca.crt

        # Same choice as Redis:
        # no = server-auth TLS only
        # remove for mTLS clients/sentinels
        tls-auth-clients no

        # Required for Sentinel -> Redis and Sentinel -> Sentinel TLS
        tls-replication yes

        protected-mode yes

persistence:
  redis-bootstrap:
    enabled: true
    type: configMap
    identifier: redis-bootstrap
    advancedMounts:
      redis:
        app:
          - path: /bootstrap/redis.conf
            subPath: redis.conf
            readOnly: true

  sentinel-bootstrap:
    enabled: true
    type: configMap
    identifier: sentinel-bootstrap
    advancedMounts:
      sentinel:
        app:
          - path: /bootstrap/sentinel.conf
            subPath: sentinel.conf
            readOnly: true

  redis-tls:
    enabled: true
    type: secret
    name: "{{ $.Release.Name }}-redis-tls"
    advancedMounts:
      redis:
        app:
          - path: /tls/tls.crt
            subPath: tls.crt
            readOnly: true
          - path: /tls/tls.key
            subPath: tls.key
            readOnly: true
          - path: /tls/ca.crt
            subPath: ca.crt
            readOnly: true

  sentinel-tls:
    enabled: true
    type: secret
    name: "{{ $.Release.Name }}-sentinel-tls"
    advancedMounts:
      sentinel:
        app:
          - path: /tls/tls.crt
            subPath: tls.crt
            readOnly: true
          - path: /tls/tls.key
            subPath: tls.key
            readOnly: true
          - path: /tls/ca.crt
            subPath: ca.crt
            readOnly: true

  redisinsight-data:
    enabled: false
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    advancedMounts:
      redisinsight:
        app:
          - path: /data

rawResources:
  redis-tls:
    enabled: true
    apiVersion: cert-manager.io/v1
    kind: Certificate
    spec:
      spec:
        secretName: "{{ $.Release.Name }}-redis-tls"
        issuerRef:
          kind: ClusterIssuer
          name: self-signed-ca
          group: cert-manager.io
        dnsNames:
          - "{{ $.Release.Name }}-redis"
          - "{{ $.Release.Name }}-redis.{{ $.Release.Namespace }}.svc"
          - "{{ $.Release.Name }}-redis.{{ $.Release.Namespace }}.svc.cluster.local"
          - "*.{{ $.Release.Name }}-redis-headless.{{ $.Release.Namespace }}.svc.cluster.local"

  sentinel-tls:
    enabled: true
    apiVersion: cert-manager.io/v1
    kind: Certificate
    spec:
      spec:
        secretName: "{{ $.Release.Name }}-sentinel-tls"
        issuerRef:
          kind: ClusterIssuer
          name: self-signed-ca
          group: cert-manager.io
        dnsNames:
          - "{{ $.Release.Name }}-sentinel"
          - "{{ $.Release.Name }}-sentinel.{{ $.Release.Namespace }}.svc"
          - "{{ $.Release.Name }}-sentinel.{{ $.Release.Namespace }}.svc.cluster.local"
          - "*.{{ $.Release.Name }}-sentinel-headless.{{ $.Release.Namespace }}.svc.cluster.local"

  redisinsight-tls:
    enabled: true
    apiVersion: cert-manager.io/v1
    kind: Certificate
    spec:
      spec:
        secretName: "{{ $.Release.Name }}-redisinsight-tls"
        issuerRef:
          kind: ClusterIssuer
          name: self-signed-ca
          group: cert-manager.io
        dnsNames:
          - "{{ $.Values.global.redisinsight.dns }}"

  redisinsight-auth:
    enabled: true
    apiVersion: traefik.io/v1alpha1
    kind: Middleware
    spec:
      spec:
        forwardAuth:
          address: 'http://{{ $.Release.Name }}-redisinsight.{{ $.Release.Namespace }}.svc.cluster.local:4180/oauth2/auth'
          trustForwardHeader: true
          authResponseHeaders:
            - X-Auth-Request-User
            - X-Auth-Request-Email
            - X-Auth-Request-Preferred-Username
            - X-Forwarded-User
  redisinsight-oauth2-errors:
    apiVersion: traefik.io/v1alpha1
    kind: Middleware
    spec:
      spec:
        errors:
          status:
            - "401-403"
          service:
            name: redis-ha-redisinsight
            port: 4180
          query: /oauth2/sign_in?rd={url}
          statusRewrites:
            "401": 302
            "403": 302
  oauth2-proxy-secret:
    enabled: true
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    spec:
      spec:
        refreshInterval: 1h0m0s
        secretStoreRef:
          name: ssegning-aws
          kind: ClusterSecretStore
        target:
          name: '{{ .Release.Name }}-oauth2-creds'
          creationPolicy: Owner
        data:
          - secretKey: client-id
            remoteRef:
              key: "prod/meta/test-app"
              property: redis_oauth2_client_id
          - secretKey: client-secret
            remoteRef:
              key: "prod/meta/test-app"
              property: redis_oauth2_secret
          - secretKey: cookie-secret
            remoteRef:
              key: "prod/meta/test-app"
              property: redis_cookie_secret