{{- range .Values.arcRunnerPools }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: arc-runner
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.6.2
      chart: app-template
      helm:
        valuesObject:
          rawResources:
            auth-secret:
              enabled: true
              apiVersion: external-secrets.io/v1
              kind: ExternalSecret
              spec:
                spec:
                  refreshInterval: 0h10m0s
                  secretStoreRef:
                    name: ssegning-aws
                    kind: ClusterSecretStore
                  target:
                    name: gh-runner-secret-pat
                    creationPolicy: Owner
                  data:
                    - secretKey: github_token
                      remoteRef:
                        key: "prod/meta/test-app"
                        property: github_token
            arc-runner-secrets:
              enabled: true
              apiVersion: external-secrets.io/v1
              kind: ExternalSecret
              spec:
                spec:
                  refreshInterval: 0h10m0s
                  secretStoreRef:
                    name: ssegning-aws
                    kind: ClusterSecretStore
                  target:
                    name: arc-runner-secrets
                    creationPolicy: Owner
                  data:
                    - secretKey: turbo-token
                      remoteRef:
                        key: "prod/artifact-cache/env"
                        property: turbo_token
                    - secretKey: access-key-id
                      remoteRef:
                        key: "prod/artifact-cache/env"
                        property: object_storage_access_key
                    - secretKey: secret-access-key
                      remoteRef:
                        key: "prod/artifact-cache/env"
                        property: object_storage_secret_key
            gh-pull-token:
              enabled: true
              apiVersion: external-secrets.io/v1
              kind: ExternalSecret
              spec:
                spec:
                  refreshInterval: 0h10m0s
                  secretStoreRef:
                    name: ssegning-aws
                    kind: ClusterSecretStore
                  target:
                    name: ghcr-pull-secret
                    creationPolicy: Owner
                    template:
                      engineVersion: v2
                      type: kubernetes.io/dockerconfigjson
                      data:
                        .dockerconfigjson: |
                          {{- $.Values.arcRunnerGhcrDockerconfigTemplate | nindent 26 }}
                  data:
                    - secretKey: github_username
                      remoteRef:
                        key: "prod/meta/test-app"
                        property: github_username
                    - secretKey: github_token
                      remoteRef:
                        key: "prod/meta/test-app"
                        property: github_token
                    - secretKey: github_email
                      remoteRef:
                        key: "prod/meta/test-app"
                        property: github_email

  destination:
    name: {{ .destinationCluster }}
    namespace: {{ .namespace }}
  syncPolicy:
    {{- if .managedNamespacePrivileged }}
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
{{- end }}
