{{ range .Values.customServices }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-{{ include "common.names.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    {{ include "common.labels.standard" $ | nindent 4 }}
  annotations:
    {{ if .useHttps }}
    traefik.ingress.kubernetes.io/service.serversscheme: "https"
    {{ end }}
spec:
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name }}-{{ include "common.names.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    {{ include "common.labels.standard" $ | nindent 4 }}
subsets:
  - addresses:
      - ip: {{ .ip }}
    ports:
      - port: {{ .port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-{{ include "common.names.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    {{ include "common.labels.standard" $ | nindent 4 }}
  annotations:
    {{ if .selfSigned }}
    cert-manager.io/cluster-issuer: cert-self-signed-ca
    {{else}}
    cert-manager.io/cluster-issuer: cert-cloudflare
    {{ end }}
    {{ with .usePriority -}}
    traefik.ingress.kubernetes.io/router.priority: "{{ . }}"
    {{ end }}

spec:
  ingressClassName: traefik
  rules:
    - host: {{ .domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .name }}-{{ include "common.names.fullname" $ }}
                port:
                  number: {{ .port }}
  tls:
    - secretName: {{ .domain }}-tls
      hosts:
        - {{ .domain }}
---
{{ end }}