applications:
  - name: cnpg
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: infrastructure
    source:
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.28.2
      chart: cloudnative-pg
      helm:
        releaseName: cnpg
        valuesObject:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
    destination:
      name: home-remote
      namespace: cnpg-system
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

  - name: cnpg-barman-cloud
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: infrastructure
    source:
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.5.0
      chart: plugin-barman-cloud
      helm:
        releaseName: cnpg-barman-cloud
        valuesObject:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
    destination:
      name: home-remote
      namespace: cnpg-system
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true


  - name: cnpg-local
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: infrastructure
    source:
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: "0.*"
      chart: cloudnative-pg
      helm:
        releaseName: cnpg
        valuesObject:
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
    destination:
      server: https://kubernetes.default.svc
      namespace: cnpg-system
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

  - name: cnpg-barman-cloud-local
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: infrastructure
    source:
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: "0.*"
      chart: plugin-barman-cloud
      helm:
        releaseName: cnpg-barman-cloud
    destination:
      server: https://kubernetes.default.svc
      namespace: cnpg-system
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

  - name: cnpg-netcup
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: infrastructure
    source:
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: "0.*"
      chart: cloudnative-pg
      helm:
        releaseName: cnpg
        valuesObject:
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
    destination:
      name: netcup-k8s
      namespace: cnpg-system
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

  - name: cnpg-barman-cloud-netcup
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: infrastructure
    source:
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: "0.*"
      chart: plugin-barman-cloud
      helm:
        releaseName: cnpg-barman-cloud
    destination:
      name: netcup-k8s
      namespace: cnpg-system
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      automated:
        prune: true
        selfHeal: true

