apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/stephane-segning/opfs-webauthn/refs/heads/main/apps/web/helm/argocd-application.example.yaml
  - https://raw.githubusercontent.com/stephane-segning/opfs-webauthn/refs/heads/main/apps/share-backend/helm/argocd-application.example.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: opfs-web
    path: opfs-web.patch.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: opfs-share-backend
    path: opfs-share-backend.patch.yaml
