resources:
  - https://raw.githubusercontent.com/stephane-segning/opfs-webauthn/refs/heads/main/apps/web/helm/argocd-application.example.yaml
  - https://raw.githubusercontent.com/stephane-segning/opfs-webauthn/refs/heads/main/apps/share-backend/helm/argocd-application.example.yaml