global:
  labels:
    app: mcpo
    team: ssegning-home

mcpo:
  controllers:
    main:
      type: deployment
      strategy: RollingUpdate
      replicas: 1
      pod:
        labels:
          app: main-app
      containers:
        mcpo:
          image:
            repository: ghcr.io/open-webui/mcpo
            tag: "git-1986204"
            pullPolicy: IfNotPresent
          
          command: /bin/sh
          
          args:
            - -c
            - |
              set -e
              mcpo --api-key $API_KEY --config=/tmp/config.json
          
          resources:
            requests:
              cpu: 400m
              memory: 2Gi
            limits:
              cpu: 800m
              memory: 4Gi
          
          envFrom:
            - secretRef:
                name: mcpo-api-key-env
            - secretRef:
                name: mcpo-env
    playwright:
      type: deployment
      strategy: RollingUpdate
      replicas: 1
      pod:
        labels:
          app: playwright-app
      containers:
        playwright:
          image:
            repository: mcr.microsoft.com/playwright
            tag: v1.53.0-noble
          
          command: /bin/sh
          
          args:
            - -c
            - |
              set -e
              
              npx -y playwright@1.53.0 run-server --port 3000 --host 0.0.0.0
          
          resources:
            requests:
              cpu: 250m
              memory: 2Gi
            limits:
              cpu: 600m
              memory: 4Gi
  
  service:
    mcpo:
      enabled: true
      annotations: { }
      type: ClusterIP
      controller: main
      ports:
        http:
          enabled: true
          port: 8000
          targetPort: 8000
    playwright:
      enabled: true
      annotations: { }
      type: ClusterIP
      controller: playwright
      ports:
        http:
          enabled: true
          port: 3000
          targetPort: 3000
  
  ingress:
    mcpo:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: self-signed-ca
      className: traefik
      hosts:
        - host: mcpo.home.ssegning
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: mcpo
                port: http
      tls:
        - secretName: mcpo-home-ssegning-tls
          hosts:
            - mcpo.home.ssegning
  
  configMaps:
    config:
      enabled: true
      annotations:
        description: 'Common configuration for the MCPo.'
      data:
        "playwright.json": |
          {
            "browser": {
              "remoteEndpoint": "ws://{{ .Release.Name }}-playwright:3000",
              "launchOptions": {
                "headless": true
              }
            },
            "vision": true
          }
        "config.json": |
          {
            "mcpServers": {
              "memory": {
                "type": "streamable_http",
                "command": "npx",
                "args": [
                  "-y",
                  "@modelcontextprotocol/server-memory"
                ]
              },
              "time": {
                "command": "uvx",
                "args": [
                  "mcp-server-time",
                  "--local-timezone=Europe/Berlin"
                ]
              },
              "fetch": {
                "command": "uvx",
                "args": [
                  "mcp-server-fetch"
                ]
              },
              "sequential-thinking": {
                "command": "npx",
                "args": [
                  "-y",
                  "@modelcontextprotocol/server-sequential-thinking"
                ]
              },
              "google-maps": {
                "command": "npx",
                "args": [
                  "-y",
                  "@modelcontextprotocol/server-google-maps"
                ],
                "env": {
                  "GOOGLE_MAPS_API_KEY": "$(GOOGLE_MAPS_API_KEY)"
                }
              },
              "brave-search": {
                "command": "npx",
                "args": [
                  "-y",
                  "@modelcontextprotocol/server-brave-search"
                ],
                "env": {
                  "BRAVE_API_KEY": "$(BRAVE_API_KEY)"
                }
              },
              "playwright": {
                "command": "npx",
                "args": [
                  "-y",
                  "@playwright/mcp@latest",
                  "--config=/tmp/playwright.json"
                ]
              }
            }
          }

  persistence:
    config:
      enabled: true
      type: configMap
      identifier: config
      advancedMounts:
        main:
          mcpo:
            - path: /tmp/config.json
              readOnly: true
              subPath: config.json
            - path: /tmp/playwright.json
              readOnly: true
              subPath: playwright.json
  