version: v1alpha1 # Indicates the schema used to decode the contents.
debug: false # Enable verbose logging to the console.
persist: true
# Provides machine specific configuration options.
machine:
  type: worker # Defines the role of the machine within the cluster.
  
  # Used to provide additional options to the kubelet.
  kubelet:
    # # The `extraMounts` field is used to add additional mounts to the kubelet container.
    extraMounts:
      - destination: "/var/mnt/longhorn" # Destination is the absolute path where the mount will be placed in the container.
        type: bind # Type specifies the mount kind.
        source: "/var/mnt/longhorn" # Source specifies the source path of the mount.
        # Options are fstab style mount options.
        options:
          - bind
          - rshared
          - rw
  
  # Used to provide instructions for installations.
  install:
    disk: /dev/sda # The disk used for installations.
    image: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b:v1.10.4 # Allows for supplying the image used to perform the installation.
    wipe: true # Indicates if the installation disk should be wiped at installation time.
  
  # # MachineSysctls usage example.
  sysctls:
    vm.nr_hugepages: "1024"
  
  # # Configures the kernel.
  kernel:
    # Kernel modules to load.
    modules:
      #- name: brtfs # Module name.
      - name: nvme_tcp
      - name: vfio_pci
  
  # # node labels example.
  nodeLabels:
    data-node: "true"
    storage: "longhorn"

# Provides cluster specific configuration options.
cluster:
  # Provides cluster specific network configuration options.
  network:
    # # The CNI used.
    cni:
      name: none # Name of CNI to use.
    #     # URLs containing manifests to apply for the CNI.
    #     urls:
    #         - https://docs.projectcalico.org/archive/v3.20/manifests/canal.yaml
  # Configures cluster member discovery.
  discovery:
    enabled: true # Enable the cluster membership discovery feature.
    # Configure registries used for cluster member discovery.
    registries:
      # Kubernetes registry uses Kubernetes API server to discover cluster members and stores additional information
      kubernetes:
        disabled: true # Disable Kubernetes discovery registry.
      # Service registry is using an external service to push and pull information about cluster members.
      service: { }
  
  # # Kube-proxy server-specific configuration options
  proxy:
    disabled: true # Disable kube-proxy deployment on cluster bootstrap.

---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn           # becomes /var/mnt/longhorn on the host
provisioning:
  minSize: 1GiB
  diskSelector:
    match: disk.dev_path == "/dev/sdb"
  grow: true             # use 100 % of the disk
filesystem:
  type: xfs