version: v1alpha1 # Indicates the schema used to decode the contents.
debug: false # Enable verbose logging to the console.
persist: true
# Provides machine specific configuration options.
machine:
  type: worker # Defines the role of the machine within the cluster.
  
  # Used to provide additional options to the kubelet.
  kubelet:
    # # The `extraMounts` field is used to add additional mounts to the kubelet container.
    extraMounts:
      - destination: "/var/mnt/longhorn" # Destination is the absolute path where the mount will be placed in the container.
        type: bind # Type specifies the mount kind.
        source: "/var/mnt/longhorn" # Source specifies the source path of the mount.
        # Options are fstab style mount options.
        options:
          - bind
          - rshared
          - rw
  
  # Used to provide instructions for installations.
  install:
    disk: /dev/sda # The disk used for installations.
    image: factory.talos.dev/installer/c35d5bd14fd96abc839f9f44f5effd00c48f654edb8a42648f4b2eb6051d1dd6:v1.12.0 # Allows for supplying the image used to perform the installation.
    wipe: true # Indicates if the installation disk should be wiped at installation time.
  
  registries:
    mirrors:
      docker.io:
        endpoints:
          - http://10.10.0.36:5100
      gcr.io:
        endpoints:
          - http://10.10.0.36:5101
      ghcr.io:
        endpoints:
          - http://10.10.0.36:5102
      registry.k8s.io:
        endpoints:
          - http://10.10.0.36:5103

  # # MachineSysctls usage example.
  sysctls:
    vm.nr_hugepages: "1024"
    net.core.bpf_jit_harden: 1
  
  # # Configures the kernel.
  kernel:
    # Kernel modules to load.
    modules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
      - name: nvme_tcp
      - name: vfio_pci
  
  # # node labels example.
  nodeLabels:
    gpu-node: "true"

# Provides cluster specific configuration options.
cluster:
  # Provides cluster specific network configuration options.
  network:
    # # The CNI used.
    cni:
      name: none # Name of CNI to use.
  
  # # Kube-proxy server-specific configuration options
  proxy:
    disabled: true # Disable kube-proxy deployment on cluster bootstrap.

---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn           # becomes /var/mnt/longhorn on the host
provisioning:
  minSize: 1GiB
  diskSelector:
    match: disk.dev_path == "/dev/sdb"
  grow: true             # use 100 % of the disk
filesystem:
  type: xfs