secretStores:
  vymalo-github:
    github:
      appID: "2926172"
      # url: Default "https://github.com/", for enterprise Github instances uncomment and add your domain like "https://github.domain.com/"
      # uploadURL: Default "https://github.com"
      auth:
        privateKey:
          name: argocd-ssegning
          key: privateKey.pem
          namespace: auth-secret
      installationID: "111824148"
      organization: "vymalo"
      #repository: "Optional. set this for repository/environment secrets"
      #environment: "Optional. set this for environment secrets"