secretStores:
  bitwarden:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: auth-secret
      organizationID: 3277a467-a991-4856-8a95-b43500e6ceb7
      projectID: fa58f07c-43f6-4f7b-9738-b43500e707cf