secretStores:
  ssegning-aws:
    aws:
      service: SecretsManager
      # define a specific role to limit access
      # to certain secrets.
      # role is a optional field that
      # can be omitted for test purposes
      role: arn:aws:iam::857285833264:role/secret-manager-k8s
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
            namespace: secret-store-system
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
            namespace: secret-store-system
