db:
  enabled: true
  instances: 2
  storage:
    size: 5Gi
    storageClass: longhorn
  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"
      
tools:
  key: "CeufBIuRu7ch5AS5MgHneg7inOsnQw0a"
  base_url: http://mcpo:8000
  tools:
    memory:
      enable: true
    time:
      enable: true
    fetch:
      enable: true
    sequential-thinking:
      enable: true
    google-maps:
      enable: true
    brave-search:
      enable: true
    playwright:
      enable: true

owu:
  podLabels:
    app.kubernetes.io/name: owui
  ollama:
    enabled: false
  tika:
    enabled: true
    fullnameOverride: owu-tika
    resources:
      limits:
        cpu: "800m"
        memory: 4000Mi
      requests:
        cpu: "200m"
        memory: 2000Mi
  openaiBaseApiUrl: "http://litellm.litellm.svc.cluster.local:4000"
  pipelines:
    enabled: true
    persistence:
      storageClass: longhorn
  sso:
    enabled: true
    enableSignup: true
    mergeAccountsByEmail: true
    oidc:
      enabled: true
      providerName: "SSegning Accounts"
      clientId: ssegning-ai
      clientExistingSecret: owui-sso
      clientExistingSecretKey: clientSecret
      providerUrl: https://accounts.ssegning.com/realms/dev/.well-known/openid-configuration
  extraEnvFrom:
    - secretRef:
        name: owui-env
  extraEnvVars:
    - name: WEBUI_URL
      value: "https://ai.ssegning.me"

    - name: S3_ADDRESSING_STYLE
      value: "path"

    - name: IMAGES_OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: owui-litellm
          key: master-key
          
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: chat-ui-app
          key: uri

    - name: ENABLE_PERSISTENT_CONFIG
      value: "False"

    - name: ENABLE_LOGIN_FORM
      value: "False"

    - name: USER_PERMISSIONS_WORKSPACE_MODELS_ACCESS
      value: "True"
    - name: USER_PERMISSIONS_WORKSPACE_KNOWLEDGE_ACCESS
      value: "True"

    - name: WEBUI_NAME
      value: "SSegning AI"
    - name: ENABLE_REALTIME_CHAT_SAVE
      value: "True"
    - name: ENABLE_CHANNELS
      value: "True"
    - name: DEFAULT_USER_ROLE
      value: "user"
    - name: TASK_MODEL
      value: "gemini-2.5-flash-preview"
    - name: TASK_MODEL_EXTERNAL
      value: "gemini-2.5-flash-preview"
    - name: ENABLE_AUTOCOMPLETE_GENERATION
      value: "False"
    - name: AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH
      value: "15"
    - name: ENABLE_COMMUNITY_SHARING
      value: "False"
    - name: WEBUI_SECRET_KEY
      value: "False"

    - name: RESET_CONFIG_ON_START
      value: "True"

    - name: DEFAULT_MODELS
      value: "o4-mini"

    - name: TOOL_SERVER_CONNECTIONS
      valueFrom:
        configMapKeyRef:
          name: tools-config
          key: tools.json

    - name: ENABLE_WEB_SEARCH
      value: "True"
    - name: WEB_SEARCH_TRUST_ENV
      value: "True"
    - name: WEB_SEARCH_RESULT_COUNT
      value: "5"
    - name: WEB_SEARCH_CONCURRENT_REQUESTS
      value: "10"
    - name: ENABLE_RAG_WEB_SEARCH
      value: "True"
    - name: WEB_SEARCH_ENGINE
      value: "brave"
    - name: BRAVE_SEARCH_API_KEY
      valueFrom:
        secretKeyRef:
          name: owui-brave
          key: brave-key

    - name: PLAYWRIGHT_WS_URL
      value: "ws://mcpo-playwright:3000"

    - name: AUDIO_STT_ENGINE
      value: "openai"
    - name: AUDIO_STT_OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: owui-litellm
          key: master-key
    - name: AUDIO_STT_MODEL
      value: "whisper-1"
    - name: AUDIO_STT_OPENAI_API_BASE_URL
      value: "http://litellm.litellm.svc.cluster.local:4000"

    - name: AUDIO_TTS_ENGINE
      value: "openai"
    - name: AUDIO_TTS_OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: owui-litellm
          key: master-key
    - name: AUDIO_TTS_MODEL
      value: "tts-1"
    - name: AUDIO_TTS_OPENAI_API_BASE_URL
      value: "http://litellm.litellm.svc.cluster.local:4000"

    - name: ENABLE_IMAGE_GENERATION
      value: "True"
    - name: IMAGE_GENERATION_ENGINE
      value: "openai"
    - name: IMAGE_GENERATION_MODEL
      value: "dall-e-3"
    - name: IMAGE_SIZE
      value: "1024x1024"
    - name: IMAGES_OPENAI_API_BASE_URL
      value: "http://litellm.litellm.svc.cluster.local:4000"

    - name: DATABASE_POOL_SIZE
      value: "5"
  
  ingress:
    enabled: true
    class: traefik
    annotations:
      cert-manager.io/cluster-issuer: cert-cloudflare
    host: ai.ssegning.me
    tls: true
  persistence:
    enabled: true
    provider: s3
    s3:
      accessKey: owui-user
      secretKeyExistingSecret: owui-minio
      secretKeyExistingSecretKey: secretKey
      endpointUrl: http://base-minio.base.svc.cluster.local:9000
      bucket: ai-apps
      keyPrefix: open-web-ui
  websocket:
    enabled: true
    url: "redis://redis-master.database.svc.cluster.local:6379"
    redis:
      enabled: false
