tools:
  key: "CeufBIuRu7ch5AS5MgHneg7inOsnQw0a"
  base_url: http://mcpo:8000
  tools:
    memory:
      enable: true
    time:
      enable: true
    fetch:
      enable: true
    puppeteer:
      enable: true
    sequential-thinking:
      enable: true
    google-maps:
      enable: true
    brave-search:
      enable: true
    playwright:
      enable: true
    scrapeless:
      enable: true
    context7:
      enable: true
    github:
      enable: true

owu:
  podLabels:
    app.kubernetes.io/name: owui
  ollama:
    enabled: false
  tika:
    enabled: true
    fullnameOverride: ui-tika
    resources:
      limits:
        cpu: "800m"
        memory: 4000Mi
      requests:
        cpu: "200m"
        memory: 2000Mi
  openaiBaseApiUrl: "http://litellm:4000"
  databaseUrl: "postgresql://home-db:3M0j0ir8o4ZysdehKWpQ6278VZOb01xV@postgresql.database.svc.cluster.local/open-web-ui"
  pipelines:
    enabled: true
    persistence:
      storageClass: nfs-ssd
  sso:
    enabled: true
    enableSignup: true
    mergeAccountsByEmail: true
    oidc:
      enabled: true
      providerName: "SSegning Accounts"
      clientId: ssegning-ai
      clientSecret: JRKDAtUYIXPeVsf0mXfvykWq7GsunL0L
      providerUrl: https://accounts.ssegning.com/realms/home/.well-known/openid-configuration
  extraEnvFrom:
    - configMapRef:
        name: tools-config
  extraEnvVars:
    - name: WEBUI_URL
      value: "https://ai.ssegning.me"

    - name: S3_ADDRESSING_STYLE
      value: "path"

    - name: OPENAI_API_KEYS
      value: "0p3n-w3bu!;sk-Wo0CXzGRj7Qwbq5evtpauQRm1xSf2TL6"
    - name: IMAGES_OPENAI_API_KEY
      value: "sk-Wo0CXzGRj7Qwbq5evtpauQRm1xSf2TL6"

    - name: ENABLE_PERSISTENT_CONFIG
      value: "False"

    - name: ENABLE_LOGIN_FORM
      value: "False"

    - name: USER_PERMISSIONS_WORKSPACE_MODELS_ACCESS
      value: "True"
    - name: USER_PERMISSIONS_WORKSPACE_KNOWLEDGE_ACCESS
      value: "True"

    - name: WEBUI_NAME
      value: "SSegning AI"
    - name: ENABLE_REALTIME_CHAT_SAVE
      value: "True"
    - name: ENABLE_CHANNELS
      value: "True"
    - name: DEFAULT_USER_ROLE
      value: "user"
    - name: TASK_MODEL
      value: "gemini-2.0-flash-lite"
    - name: TASK_MODEL_EXTERNAL
      value: "gemini-2.0-flash-lite"
    - name: ENABLE_AUTOCOMPLETE_GENERATION
      value: "False"
    - name: AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH
      value: "15"
    - name: ENABLE_COMMUNITY_SHARING
      value: "False"
    - name: WEBUI_SECRET_KEY
      value: "False"

    - name: RESET_CONFIG_ON_START
      value: "True"

    - name: DEFAULT_MODELS
      value: "o4-mini"

    - name: TOOL_SERVER_CONNECTIONS
      valueFrom:
        configMapKeyRef:
          name: tools-config
          key: tools.json

    - name: ENABLE_WEB_SEARCH
      value: "True"
    - name: WEB_SEARCH_TRUST_ENV
      value: "True"
    - name: WEB_SEARCH_RESULT_COUNT
      value: "5"
    - name: WEB_SEARCH_CONCURRENT_REQUESTS
      value: "10"
    - name: ENABLE_RAG_WEB_SEARCH
      value: "True"
    - name: WEB_SEARCH_ENGINE
      value: "brave"
    - name: BRAVE_SEARCH_API_KEY
      value: "BSANwjGlraxhj0g-7gF06XzV5W0Sfm4"

    - name: PLAYWRIGHT_WS_URL
      value: "ws://mcpo-playwright:3000/plw"

    - name: AUDIO_STT_ENGINE
      value: "openai"
    - name: AUDIO_STT_OPENAI_API_KEY
      value: "sk-Wo0CXzGRj7Qwbq5evtpauQRm1xSf2TL6"
    - name: AUDIO_STT_MODEL
      value: "whisper-1"
    - name: AUDIO_STT_OPENAI_API_BASE_URL
      value: "http://litellm:4000"

    - name: AUDIO_TTS_ENGINE
      value: "openai"
    - name: AUDIO_TTS_OPENAI_API_KEY
      value: "sk-Wo0CXzGRj7Qwbq5evtpauQRm1xSf2TL6"
    - name: AUDIO_TTS_MODEL
      value: "tts-1"
    - name: AUDIO_TTS_OPENAI_API_BASE_URL
      value: "http://litellm:4000"

    - name: ENABLE_IMAGE_GENERATION
      value: "True"
    - name: IMAGE_GENERATION_ENGINE
      value: "openai"
    - name: IMAGE_GENERATION_MODEL
      value: "dall-e-3"
    - name: IMAGE_SIZE
      value: "1024x1024"
    - name: IMAGES_OPENAI_API_BASE_URL
      value: "http://litellm:4000"

    - name: DATABASE_POOL_SIZE
      value: "5"
  
  ingress:
    enabled: true
    class: traefik
    annotations:
      cert-manager.io/cluster-issuer: cert-home-cert-cloudflare
    host: ai.ssegning.me
    tls: true
  persistence:
    enabled: true
    provider: s3
    s3:
      accessKey: ai-apps-user
      secretKey: oNVrVdctFMfgq3clyPYkFq97d46QyFZJD3tjO66KtFg9B2rf
      endpointUrl: http://base-minio.base.svc.cluster.local:9000
      bucket: ai-apps
      keyPrefix: open-web-ui
  websocket:
    enabled: true
    url: "redis://redis-master.database.svc.cluster.local:6379"
    redis:
      enabled: false
