global:
  security:
    allowInsecureImages: true


minio:
  defaultInitContainers:
    volumePermissions:
      image:
        repository: bitnamilegacy/os-shell

  image:
    repository: bitnamilegacy/minio
  enabled: true
  mode: standalone
  auth:
    existingSecret: minio-root
  persistence:
    storageClass: sstorage
    size: 200Gi
  service:
    type: ClusterIP
  clientImage:
    repository: bitnamilegacy/minio-client
  console:
    image:
      repository: bitnamilegacy/minio-object-browser
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: s3-admin.ssegning.me
      annotations:
        cert-manager.io/cluster-issuer: cert-cloudflare
      tls: true
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: s3.ssegning.me
    annotations:
      cert-manager.io/cluster-issuer: cert-cloudflare
    tls: true
    extraHosts:
      - name: s3.camer.digital
        path: /

  provisioning:
    enabled: true
    
    policies:
      - name: monitoring-policy
        statements:
          - actions:
              - "s3:*"
            effect: "Allow"
            resources:
              - "arn:aws:s3:::monitoring/*"
              - "arn:aws:s3:::monitoring"
              - "arn:aws:s3:::monitoring-loki-ruler/*"
              - "arn:aws:s3:::monitoring-loki-ruler"
              - "arn:aws:s3:::monitoring-loki-chunks/*"
              - "arn:aws:s3:::monitoring-loki-chunks"
              - "arn:aws:s3:::monitoring-tempo/*"
              - "arn:aws:s3:::monitoring-tempo"
      - name: lakefs-policy
        statements:
          - actions:
              - "s3:*"
            effect: "Allow"
            resources:
              - "arn:aws:s3:::lakefs/*"
              - "arn:aws:s3:::lakefs"
      - name: argo-workflow-policy
        statements:
          - actions:
              - "s3:*"
            effect: "Allow"
            resources:
              - "arn:aws:s3:::argo-artifacts/*"
              - "arn:aws:s3:::argo-artifacts"
    
    usersExistingSecrets:
      - minio-users
    
    buckets:
      - name: monitoring
        withLock: false
      - name: lakefs
        withLock: false
      - name: mlflow
        withLock: false
      - name: argo-artifacts
        withLock: false

provision_minio_buckets_policies:
  enabled: true
  secret: minio-root
  policies:
    - name: lakefs
      policy:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": { "AWS": [ "*" ] },
              "Action": [ "s3:GetObject" ],
              "Resource": [
                "arn:aws:s3:::lakefs/public/*"
              ]
            }
          ]
        }