db:
  enabled: true
  instances: 2
  storage:
    size: 10Gi
    storageClass: longhorn
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

gitea:
  valkey-cluster:
    enabled: false
  valkey:
    enabled: false
  postgresql:
    enabled: false
  postgresql-ha:
    enabled: false

  persistence:
    enabled: false
    storageClass: longhorn
  
  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: cert-home-cert-cloudflare
    hosts:
      - host: vsc.ssegning.me
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: vsc-ssegning-me-tls
        hosts:
          - vsc.ssegning.me
  
  gitea:
    admin:
      existingSecret: "gitea-admin-secret"
      email: "vsc@ssegning.com"
#    oauth: 
#      - name: "SSegning Accounts Dev"
#        provider: oauth2
#        existingSecret: gitea-oauth2
#        autoDiscoverUrl: https://accounts.ssegning.com/realms/dev 
    additionalConfigFromEnvs:
      - name: GITEA__DATABASE__HOST
        valueFrom:
          secretKeyRef:
            key: host
            name: vsc-pg-app
      - name: GITEA__DATABASE__PASSWD
        valueFrom:
          secretKeyRef:
            key: password
            name: vsc-pg-app
      - name: GITEA__DATABASE__NAME
        valueFrom:
          secretKeyRef:
            key: dbname
            name: vsc-pg-app
      - name: GITEA__DATABASE__USER
        valueFrom:
          secretKeyRef:
            key: user
            name: vsc-pg-app
    config:
      database:
        DB_TYPE: postgres
      
      session:
        PROVIDER: redis
        PROVIDER_CONFIG: redis://redis-master.database.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
      
      cache:
        ENABLED: true
        ADAPTER: redis
        HOST: redis://redis-master.database.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
      
      queue:
        TYPE: redis
        CONN_STR: redis://redis-master.database.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&


actions: 
  enabled: true
  statefulset: 
    timezone: Europe/Berlin
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "1"
  giteaRootURL: "http://vsc-gitea-http:3000"
  existingSecret: "gitea-action-secret"
  existingSecretKey: "token"

action-pool: 
  enabled: true
  statefulset: 
    timezone: Europe/Berlin
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "1"
      
  giteaRootURL: "http://vsc-gitea-http:3000"
  existingSecret: "gitea-action-secret"
  existingSecretKey: "token"
  