---
{{- with .Values.db }}
{{- if .enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "common.names.fullname" $ }}-pg
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{ include "common.labels.standard" $ | nindent 4 }}
spec:
  instances: {{ include "common.tplvalues.render" ( dict "value" .instances "context" $ ) }}

  storage:
    size: {{ include "common.tplvalues.render" ( dict "value" .storage.size "context" $ ) }}
    storageClass: {{ include "common.tplvalues.render" ( dict "value" .storage.storageClass "context" $ ) }}

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: {{ include "common.names.fullname" $ }}-pg
  resources: {{ include "common.tplvalues.render" ( dict "value" .resources "context" $ ) | nindent 4 }}

{{ with .backup }}
{{ if .enabled }}
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ include "common.names.fullname" $ }}-pg
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{ include "common.labels.standard" $ | nindent 4 }}
spec:
  configuration:
    destinationPath: {{ include "common.tplvalues.render" ( dict "value" .s3.destinationPath "context" $ ) }}
    s3Credentials: {{ include "common.tplvalues.render" ( dict "value" .s3.credentials "context" $ ) | nindent 6 }}
    wal:
      compression: gzip
  retentionPolicy: {{ include "common.tplvalues.render" ( dict "value" .retentionPolicy "context" $ ) }}

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "common.names.fullname" $ }}-pg
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{ include "common.labels.standard" $ | nindent 4 }}
spec:
  cluster:
    name: {{ include "common.names.fullname" $ }}-pg
  schedule: {{ include "common.tplvalues.render" ( dict "value" .schedule "context" $ ) }}
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
{{ end }}
{{ end }}
{{ end }}
{{ end }}