{{/*
Build TOOL_SERVER_CONNECTIONS as JSON.

Values expected under .Values.tools:

  base_url: "http://mcpo:8000"
  key:      "sk-…"
  tools:    # list (or map) of tool names to expose
    brave-search: {}
    fetch:         {}
    google-maps:   {}
    …

*/}}

{{ define "tool_server" -}}
{{ $cfg := .Values.tools -}}
{{- if not $cfg }}[ ]{{ else -}}

  {{/* $items will become the slice we serialise */}}
  {{- $items := list -}}

  {{- range $name, $v := $cfg.tools }}
    {{- $item := dict
        "url"        (printf "%s/%s" $cfg.base_url $name)
        "path"       "openapi.json"
        "auth_type"  "bearer"
        "key"        $cfg.key
        "config" (dict
            "enable"         $v.enable
            "access_control" (dict
                "read"  (dict "group_ids" (list) "user_ids" (list))
                "write" (dict "group_ids" (list) "user_ids" (list)))) -}}

    {{- $items = append $items $item -}}
  {{- end -}}

  {{ $items | toPrettyJson -}}
{{ end -}}
{{- end -}}
