{{ with .Values.solvers.selfSigned }}
{{ if .enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "common.names.fullname" $ }}-self-signed
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{ include "common.labels.standard" $ | nindent 4 }}
  annotations:
    {{- with .commonAnnotations }}
    {{ include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
    {{- end }}
    {{- with $.Values.commonAnnotations }}
    {{ include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  isCA: true
  commonName: "Home SSegning Root CA"
  secretName: self-signed-ca
  duration: 87600h # 10 years
  privateKey:
    algorithm: ECDSA
    size: 256

  issuerRef:
    name: {{ include "common.names.fullname" $ }}-self-signed-basic
    kind: ClusterIssuer
    group: cert-manager.io
{{ end }}
{{ end }}