db:
  enabled: true
  instances: 2
  storage:
    size: 5Gi
    storageClass: longhorn
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

mlflow:
  replicaCount: 1

  image:
    repository: burakince/mlflow
    pullPolicy: IfNotPresent
    tag: "3.7.0"

  extraFlags:
    allowedHosts: "mlflow.home.ssegning"
    corsAllowedOrigins: "https://mlflow.home.ssegning"

  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: self-signed-ca
    hosts:
      - host: mlflow.home.ssegning
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: mlflow.home.ssegning-tls
        hosts:
          - mlflow.home.ssegning

  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

  extraEnvVars:
    MLFLOW_S3_IGNORE_TLS: true  # Skip TLS certificate verification for S3
    MLFLOW_S3_ENDPOINT_URL: http://s3-minio.s3.svc.cluster.local:9000

  artifactRoot:
    defaultArtifactRoot: "./mlruns"
    defaultArtifactsDestination: "./mlartifacts"
    s3:
      enabled: true
      bucket: mlflow
      existingSecret:
        name: mlflow-env
        keyOfAccessKeyId: "s3-access-key"
        keyOfSecretAccessKey: "s3-secret-key"

  backendStore:
    postgres:
      enabled: true
      host: 'mlflow-pg'
      database: app

    existingDatabaseSecret:
      name: 'mlflow-pg-app'