db:
  enabled: true
  instances: 2
  storage:
    size: 5Gi
    storageClass: longhorn
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

lakefs:
  replicaCount: 1

  image:
    pullPolicy: IfNotPresent

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: self-signed-ca
    hosts:
      - host: lakefs.home.ssegning
        paths:
          - "/"
    tls:
      - secretName: lakefs.home.ssegning-tls
        hosts:
          - lakefs.home.ssegning

  existingSecret: 'lakefs-env'

  secretKeys:
    authEncryptSecretKey: auth-secret

  extraEnvVars:
    - name: LAKEFS_DATABASE_TYPE
      value: postgres
    - name: LAKEFS_DATABASE_POSTGRES_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: 'lakefs-env'
          key: postgres-uri
    - name: LAKEFS_BLOCKSTORE_TYPE
      value: s3
    - name: LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: 'lakefs-env'
          key: s3-access-key
    - name: LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: 'lakefs-env'
          key: s3-secret-key
    - name: LAKEFS_BLOCKSTORE_S3_ENDPOINT
      value: http://s3-minio.s3.svc.cluster.local:9000
    - name: LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE
      value: "true"
    - name: LAKEFS_BLOCKSTORE_S3_DISCOVER_BUCKET_REGION
      value: "false"


  lakefsConfig: |
    database:
      type: postgres
    blockstore:
      type: s3

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

  service:
    type: ClusterIP
    port: 80