longhorn:
  persistence:
    defaultClass: false
    defaultClassReplicaCount: 2
  defaultSettings:
    defaultDataPath: "/var/mnt/longhorn"
  ingress:
    enabled: true
    ingressClassName: traefik
    host: longhorn.home.ssegning
    tls: true
    tlsSecret: longhorn.home.ssegning-tls
    
    
nfs-ssd:
  storageClass:
    defaultClass: false
    pathPattern: 'home-apps/${.PVC.namespace}/${.PVC.name}'
    name: nfs-ssd
    reclaimPolicy: Retain
  nfs:
    server: "10.10.0.227"
    path: "/ssd_pool"

nfs-off-topic:
  storageClass:
    defaultClass: false
    pathPattern: 'pvcs/${.PVC.namespace}/${.PVC.name}'
    name: nfs-off-topic
    reclaimPolicy: Retain
  nfs:
    server: "10.10.0.227"
    path: "/backup_pool"