global: 
  imageRegistry: container-registry.home.ssegning/docker

longhorn:
  nameOverride: longhorn 
  persistence:
    defaultClass: false
    defaultClassReplicaCount: 2
  defaultSettings:
    defaultDataPath: "/var/mnt/longhorn"
  defaultBackupStore:
    backupTarget: nfs://10.10.0.36:/volume1/k8s/backup
    
  ingress:
    enabled: true
    ingressClassName: traefik
    host: longhorn.home.ssegning
    annotations:
      cert-manager.io/cluster-issuer: self-signed-ca
    tls: true
    tlsSecret: longhorn.home.ssegning-tls
sstorage:
  fullnameOverride: sstorage
  storageClass:
    defaultClass: true
    pathPattern: 'pvcs/${.PVC.namespace}/${.PVC.name}'
    name: sstorage
    reclaimPolicy: Retain
  nfs:
    server: "10.10.0.36"
    path: "/volume1/k8s"
