longhorn:
  persistence:
    defaultClass: false
    defaultClassReplicaCount: 2
  defaultSettings:
    defaultDataPath: "/var/mnt/longhorn"
  ingress:
    enabled: true
    ingressClassName: traefik
    host: longhorn.home.ssegning
    tls: true
    tlsSecret: longhorn.home.ssegning-tls