apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: artifact-cache-users
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ssegning-aws
    kind: ClusterSecretStore
  target:
    name: artifact-cache-users
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        artifact-cache-user: |
          username={{ `{{ .access }}` }}
          password={{ `{{ .secret }}` }}
          disabled=false
          policies=artifact-cache-policy
  data:
    - secretKey: access
      remoteRef:
        key: prod/artifact-cache/env
        property: object_storage_access_key
    - secretKey: secret
      remoteRef:
        key: prod/artifact-cache/env
        property: object_storage_secret_key
