apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: artifact-cache-users
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    {{ include "common.labels.standard" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ssegning-aws
    kind: ClusterSecretStore
  target:
    name: artifact-cache-users
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        artifact-cache-user: |
          username={{ `{{ .access }}` }}
          password={{ `{{ .secret }}` }}
          disabled=false
          policies=artifact-cache-policy
  data:
    - secretKey: access
      remoteRef:
        key: prod/artifact-cache/env
        property: object_storage_access_key
    - secretKey: secret
      remoteRef:
        key: prod/artifact-cache/env
        property: object_storage_secret_key
