apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-minio
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: sstorage
  volumeMode: Filesystem
