apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tempo-otlp
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{ include "common.labels.standard" $ | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: cert-cloudflare
spec:
  rules:
    - host: otlp.ssegning.com
      http:
        paths:
          - backend:
              service:
                name: tempo
                port:
                  name: tempo-otlp-http
            path: /
            pathType: Prefix
  tls:
    - secretName: otlp.ssegning.com-tls
      hosts:
        - otlp.ssegning.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tempo-local
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{ include "common.labels.standard" $ | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: self-signed-ca
spec:
  rules:
    - host: tempo.home.ssegning
      http:
        paths:
          - backend:
              service:
                name: tempo
                port:
                  name: tempo-otlp-http
            path: /
            pathType: Prefix
  tls:
    - secretName: otlp.home.ssegning-tls
      hosts:
        - tempo.home.ssegning