
global:
  issuer:
    email: "selastlambou@protonmail.com"

solvers:
  cloudflare:
    enabled: true
    enabledStaging: false
    email: "{{ .Values.global.issuer.email }}"
    commonAnnotations: ~
  http:
    enabled: true
    enabledStaging: true
    ingressClassName: "traefik"
    email: "{{ .Values.global.issuer.email }}"
    commonAnnotations: ~
  selfSigned:
    enabled: true
    enabledStaging: true
    commonAnnotations: ~

commonAnnotations:
  "helm.sh/hook": "post-install,post-upgrade,pre-delete"
  #"helm.sh/hook-delete-policy": "hook-succeeded"
  "helm.sh/hook-weight": "10"

cert-manager:
  installCRDs: true